"""
restriction_engine.py — Phase 6: Step 6
System 3: Dynamic Update / Restriction Engine.
Translates predictions from System 2 into stateful simulation constraints.

Responsibilities:
1. Evaluates ConditionPrediction probabilities against calibration thresholds.
2. Manages restriction lifecycle: ACTIVE, UPDATED, UNCHANGED, EXPIRED, REMOVED.
3. Prevents duplicate active restrictions across 30-second simulation steps.
4. Tags all generated constraints with source = "PREDICTED_SYNTHETIC".
5. Emits effective speed caps to System 1 Physics Simulator.
"""

import os
import json
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, Any, List, Optional

from src.data_generator.prediction_engine import ConditionPrediction

# Automatically detect project root
PROJECT_ROOT = Path(__file__).resolve().parents[2]


@dataclass
class SyntheticRestriction:
    """Dataclass representing a dynamic synthetic restriction generated by System 3."""
    restriction_id: str
    source: str                      # "PREDICTED_SYNTHETIC"
    condition_type: str              # "CONGESTION" | "FOG" | "OPERATIONAL_RISK"
    status: str                      # "ACTIVE" | "UPDATED" | "UNCHANGED" | "EXPIRED" | "REMOVED"
    restriction_speed_kmph: float    # e.g., 25.0, 40.0, 60.0
    start_time: str
    last_updated_time: str
    target_section_id: str
    target_position_km: float
    description: str

    def to_dict(self) -> Dict[str, Any]:
        """Converts restriction to a plain dictionary."""
        return asdict(self)


class RestrictionEngine:
    """
    System 3 Restriction Decision Engine & State Machine.
    """

    def __init__(
        self,
        calibration_filepath: str = str(PROJECT_ROOT / "config" / "historical_calibration.json")
    ):
        print(f"[System3 RestrictionEngine] Loading thresholds from: {calibration_filepath}")
        if not os.path.exists(calibration_filepath):
            raise FileNotFoundError(f"Calibration file not found at: {calibration_filepath}")

        with open(calibration_filepath, "r", encoding="utf-8") as f:
            self.config = json.load(f)

        self.thresholds = self.config.get("speed_impact_thresholds", {})
        
        # Stateful registry for active synthetic restrictions
        self.active_restrictions: Dict[str, SyntheticRestriction] = {}
        self.restriction_counter = 1

    def evaluate_prediction(
        self,
        prediction: ConditionPrediction,
        current_state: Dict[str, Any]
    ) -> List[SyntheticRestriction]:
        """
        Evaluates System 2 prediction against thresholds and updates active restrictions.
        Returns all current effective synthetic restrictions.
        """
        timestamp = prediction.prediction_timestamp
        current_section = current_state.get("current_section_id", "UNKNOWN_SECTION")
        current_pos_km = float(current_state.get("current_position_km", 0.0))

        effective_restrictions: List[SyntheticRestriction] = []

        # --- 1. Evaluate Congestion Risk ---
        cong_high_thresh = self.thresholds.get("HIGH_CONGESTION", {}).get("probability_threshold", 0.70)
        cong_med_thresh = self.thresholds.get("MEDIUM_CONGESTION", {}).get("probability_threshold", 0.45)

        target_cong_speed = None
        cong_level_name = None

        if prediction.congestion_risk >= cong_high_thresh:
            target_cong_speed = self.thresholds.get("HIGH_CONGESTION", {}).get("restriction_speed_kmph", 25.0)
            cong_level_name = "HIGH"
        elif prediction.congestion_risk >= cong_med_thresh:
            target_cong_speed = self.thresholds.get("MEDIUM_CONGESTION", {}).get("restriction_speed_kmph", 60.0)
            cong_level_name = "MEDIUM"

        res_key_cong = "PRED_CONG_01"

        if target_cong_speed is not None:
            if res_key_cong in self.active_restrictions:
                # Existing restriction: check if speed cap updated (strengthened / weakened)
                existing = self.active_restrictions[res_key_cong]
                if existing.restriction_speed_kmph != target_cong_speed:
                    existing.restriction_speed_kmph = target_cong_speed
                    existing.status = "UPDATED"
                    existing.description = f"Predicted {cong_level_name} Congestion (Speed adjusted to {target_cong_speed} km/h)"
                else:
                    existing.status = "UNCHANGED"
                existing.last_updated_time = timestamp
                effective_restrictions.append(existing)
            else:
                # New restriction: CREATE ACTIVE
                new_res = SyntheticRestriction(
                    restriction_id=res_key_cong,
                    source="PREDICTED_SYNTHETIC",
                    condition_type="CONGESTION",
                    status="ACTIVE",
                    restriction_speed_kmph=target_cong_speed,
                    start_time=timestamp,
                    last_updated_time=timestamp,
                    target_section_id=current_section,
                    target_position_km=current_pos_km,
                    description=f"Predicted {cong_level_name} Congestion (Speed cap {target_cong_speed} km/h)"
                )
                self.active_restrictions[res_key_cong] = new_res
                effective_restrictions.append(new_res)
        else:
            # Risk dropped below threshold: EXPIRE restriction if it was active
            if res_key_cong in self.active_restrictions:
                expired_res = self.active_restrictions.pop(res_key_cong)
                expired_res.status = "EXPIRED"
                expired_res.last_updated_time = timestamp
                # Emitted once as EXPIRED then removed
                effective_restrictions.append(expired_res)

        # --- 2. Evaluate Fog Risk ---
        fog_thresh = self.thresholds.get("FOG_RESTRICTION", {}).get("probability_threshold", 0.40)
        res_key_fog = "PRED_FOG_01"

        if prediction.fog_risk >= fog_thresh:
            target_fog_speed = self.thresholds.get("FOG_RESTRICTION", {}).get("restriction_speed_kmph", 40.0)

            if res_key_fog in self.active_restrictions:
                existing_fog = self.active_restrictions[res_key_fog]
                existing_fog.status = "UNCHANGED"
                existing_fog.last_updated_time = timestamp
                effective_restrictions.append(existing_fog)
            else:
                new_fog = SyntheticRestriction(
                    restriction_id=res_key_fog,
                    source="PREDICTED_SYNTHETIC",
                    condition_type="FOG",
                    status="ACTIVE",
                    restriction_speed_kmph=target_fog_speed,
                    start_time=timestamp,
                    last_updated_time=timestamp,
                    target_section_id=current_section,
                    target_position_km=current_pos_km,
                    description=f"Predicted Fog Visibility Risk (Speed cap {target_fog_speed} km/h)"
                )
                self.active_restrictions[res_key_fog] = new_fog
                effective_restrictions.append(new_fog)
        else:
            if res_key_fog in self.active_restrictions:
                expired_fog = self.active_restrictions.pop(res_key_fog)
                expired_fog.status = "EXPIRED"
                expired_fog.last_updated_time = timestamp
                effective_restrictions.append(expired_fog)

        return effective_restrictions

    def resolve_effective_speed_cap(self, restrictions: List[SyntheticRestriction]) -> float:
        """
        Returns the minimum speed cap across all active synthetic restrictions (999.0 if no restrictions).
        """
        min_speed = 999.0
        for r in restrictions:
            if r.status in ["ACTIVE", "UPDATED", "UNCHANGED"]:
                min_speed = min(min_speed, r.restriction_speed_kmph)
        return min_speed


if __name__ == "__main__":
    from src.data_generator.prediction_engine import ConditionPrediction

    engine = RestrictionEngine()

    mock_state = {
        "timestamp": "08:30:00",
        "current_position_km": 145.0,
        "current_section_id": "SEC_MTC_MOZ",
        "current_delay_min": 18.0
    }

    # Step 1: Medium Congestion Prediction
    pred1 = ConditionPrediction(
        prediction_timestamp="08:30:00",
        prediction_horizon_min=30.0,
        congestion_risk=0.55,
        fog_risk=0.20,
        delay_risk=0.40,
        expected_speed_impact="MEDIUM",
        predicted_condition_summary="MODERATE CONGESTION PREDICTED",
        prediction_source="BASELINE_HISTORICAL_PRIOR"
    )

    res1 = engine.evaluate_prediction(pred1, mock_state)
    speed_cap1 = engine.resolve_effective_speed_cap(res1)

    print("\n" + "=" * 80)
    print("SYSTEM 3 RESTRICTION ENGINE TEST — STEP 1 (t=08:30:00)")
    print("=" * 80)
    print(f"Active Restrictions Count : {len(res1)}")
    for r in res1:
        print(f"  [{r.restriction_id}] {r.condition_type} -> Status: {r.status}, Speed: {r.restriction_speed_kmph} km/h")
    print(f"Effective Speed Cap       : {speed_cap1} km/h")

    # Step 2: Escalated High Congestion Prediction at t=08:30:30
    mock_state["timestamp"] = "08:30:30"
    pred2 = ConditionPrediction(
        prediction_timestamp="08:30:30",
        prediction_horizon_min=30.0,
        congestion_risk=0.75,
        fog_risk=0.20,
        delay_risk=0.60,
        expected_speed_impact="SEVERE",
        predicted_condition_summary="HIGH CONGESTION PREDICTED",
        prediction_source="BASELINE_HISTORICAL_PRIOR"
    )

    res2 = engine.evaluate_prediction(pred2, mock_state)
    speed_cap2 = engine.resolve_effective_speed_cap(res2)

    print("\n" + "=" * 80)
    print("SYSTEM 3 RESTRICTION ENGINE TEST — STEP 2 (t=08:30:30, Escalated)")
    print("=" * 80)
    print(f"Active Restrictions Count : {len(res2)}")
    for r in res2:
        print(f"  [{r.restriction_id}] {r.condition_type} -> Status: {r.status}, Speed: {r.restriction_speed_kmph} km/h")
    print(f"Effective Speed Cap       : {speed_cap2} km/h")

    # Step 3: Risk Drops to Normal at t=08:31:00
    mock_state["timestamp"] = "08:31:00"
    pred3 = ConditionPrediction(
        prediction_timestamp="08:31:00",
        prediction_horizon_min=30.0,
        congestion_risk=0.20,
        fog_risk=0.10,
        delay_risk=0.10,
        expected_speed_impact="NONE",
        predicted_condition_summary="NORMAL CONDITIONS PREDICTED",
        prediction_source="BASELINE_HISTORICAL_PRIOR"
    )

    res3 = engine.evaluate_prediction(pred3, mock_state)
    speed_cap3 = engine.resolve_effective_speed_cap(res3)

    print("\n" + "=" * 80)
    print("SYSTEM 3 RESTRICTION ENGINE TEST — STEP 3 (t=08:31:00, Cleared)")
    print("=" * 80)
    print(f"Active Restrictions Count : {len(res3)}")
    for r in res3:
        print(f"  [{r.restriction_id}] {r.condition_type} -> Status: {r.status}, Speed: {r.restriction_speed_kmph} km/h")
    print(f"Effective Speed Cap       : {speed_cap3} km/h")
    print("=" * 80)
